---
  kind: pipeline
  type: docker
  name: build
  
  steps:
  - name: build 
    image: node
    failure: ignore
    commands:
    - npm install
    - npm run build


  - name: package docker 
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: zhangwenjie/robert-shop
      username:
        from_secret: docker_username
      password:
        from_secret: docker_pasword
      tags: 
      - latest

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: ding_token
      tips_title: "Build Status"
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
      tpl: drone.tpl
    when:
      status:
      - failure
      - success

---
kind: pipeline
name: deployment
type: docker

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  environment:
    projectName: robert-shop
    imageName: zhangwenjie/robert-shop
    version: latest

  settings:
    host: www.robertzwj.com
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    script:
    - sh deploy.sh
      

depends_on:
- build


    
  