---
  kind: pipeline
  type: docker
  name: build
  
  steps:
  - name: build 
    image: node
    failure: ignore
    commands:
    - env
    - npm install
    - npm run build


  - name: package docker 
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: zhangwenjie/robert-shop
      username:
        from_secret: docker_username
      password:
        from_secret: docker_pasword
      tags: 
      - latest

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: ding_token
      tips_title: "Build Status"
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
      tpl: drone.tpl
    when:
      status:
      - failure
      - success

---
kind: pipeline
name: deployment
type: docker

steps:
- name: scp deploy file
  image: appleboy/drone-scp
  settings:
    host: www.robertzwj.com
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    target: /tmp/deploy/${DRONE_REPO_NAME}/
    source: deploy.sh

- name: ssh to deploy
  image: appleboy/drone-ssh
  environment:
    projectName: robert-shop
    imageName: zhangwenjie/robert-shop
    version: latest

  settings:
    host: www.robertzwj.com
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    script:
    - cd /tmp/deploy/${DRONE_REPO_NAME}/
    - export projectName=${projectName}
    - export imageName=${imageName}
    - export version=${version}
    - sh deploy.sh
      

depends_on:
- build


    
  
