---
kind: pipeline
type: docker
name: build

steps:
- name: build 
  image: node
  failure: ignore
  commands:
  - npm install
  - npm run build

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host: http://sonar.robertzwj.com
    sonar_token:
      from_secret: sonar_token
    sources: src/
    showProfiling: true
    level: DEBUG
    timeout: 20
    ver: 1.0


- name: package docker 
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: zhangwenjie/robert-shop
    username:
      from_secret: docker_username
    password:
      from_secret: docker_pasword
    tags: ${DRONE_COMMIT_SHA:0:8}
    

- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token:
      from_secret: ding_token
    tips_title: "Build Status"
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
    tpl: drone-build.tpl
  when:
    status:
    - failure
    - success
---
kind: pipeline
name: deployment
type: docker

steps:
- name: scp deploy file
  image: appleboy/drone-scp
  settings:
    host: www.robertzwj.com
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    target: /tmp/deploy/${DRONE_REPO_NAME}/
    source: deploy.sh

- name: ssh to deploy
  image: appleboy/drone-ssh
  settings:
    host: www.robertzwj.com
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    script:
    - env
    - cd /tmp/deploy/${DRONE_REPO_NAME}/
    - export projectName=${DRONE_REPO_NAME}
    - export imageName=zhangwenjie/${DRONE_REPO_NAME}
    - export version=${DRONE_COMMIT_SHA:0:8}
    - sh deploy.sh

- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token:
      from_secret: ding_token
    tips_title: "Deploy Status"
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
    tpl: drone-deploy.tpl
  when:
    status:
    - failure
    - success

depends_on:
- build


    
  
