stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm run build
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: zhangwenjie/robert-shop
      pushRemote: true
      registry: 127.0.0.1:34808
timeout: 60
notification: {}
